default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: wowgroups
  password: 123456
  pool: 5

development:
  <<: *default
  database: WoWGroups_development


test:
  <<: *default
  database: WoWGroups_test
