default: &default
  adapter: postgresql
  encoding: unicode
  username: wowgroups
  pool: 5

production:
  <<: *default
  host: 127.0.0.1
  database: WoWGroups_production
  password: <%= Rails.application.credentials.postgresql_password %>

development:
  <<: *default
  host: localhost
  database: WoWGroups_development
  password: 123456


test:
  <<: *default
  host: localhost
  database: WoWGroups_test
  password: 123456
